baseURL = "https://www.BlogDeSara.com/"
languageCode = "es-es"
title = "SaruCodes"
theme = "hugo-theme-stack"

# Parametros del sitio
[params]
# Información del autor
[params.author]
name = "Sara"
email = "sara@example.com"
image = "images/author/sara.jpg"  # (opcional)

# Otros parámetros generales


# Menu
[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "about"
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
identifier = "apuntes"
name = "Apuntes"
url = "/apuntes/"
weight = 2

[[menu.main]]
identifier = "markdown"
name = "Markdown"
url = "/markdown/"
weight = 3

[[menu.main]]
identifier = "tele"
name = "Television"
url = "/television/"
weight = 3

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/hugo-theme-stack"
params.icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"
params.icon = "brand-twitter"


